config/routes.rb
Rails.application.routes.draw do
  resource :registrations, only: [:new, :create]
  resource :session
  resources :passwords, param: :token
  resources :urls
  resources :links
  resources :link_kinds
  resources :edition_positions
  resources :edition_sections
  resources :editions
  resources :archetypes
  resources :artist_credit_participants
  resources :artist_credits
  resources :participants

  get "home", to: "home#index"
  resources :import_orders
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource :password, only: [:edit, :update]
  namespace :identity do
    resource :email, only: [:edit, :update]
    resource :email_verification, only: [:edit, :create]
    resource :password_reset, only: [:new, :edit, :create, :update]
  end
  root "main#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/album_archetype.rb
class AlbumArchetype < ApplicationRecord
  include Archetypeable
end

app/models/album_edition.rb
class AlbumEdition < ApplicationRecord
  include Editionable
end

app/models/archetype.rb
class Archetype < ApplicationRecord
  include Centralable
  include Linkable

  delegated_type :archetypeable, types: %w[AlbumArchetype SongArchetype]

  belongs_to :artist_credit, optional: true
  has_many :editions
end

app/models/artist_credit.rb
class ArtistCredit < ApplicationRecord
  has_many :participants, class_name: "ArtistCreditParticipant", dependent: :destroy

  before_validation :ensure_name_has_a_value

  validates :name, presence: true, uniqueness: true

  private

  def ensure_name_has_a_value
    return if name.present?

    pairs = participants.map { |acp| [acp.name, join_phrase_for(acp)] }.flatten
    pairs.pop # ignore the last join_phrase
    self.name = pairs.join
  end

  def join_phrase_for(artist_credit_participant)
    artist_credit_participant.join_phrase || " "
  end
end

app/models/central.rb
class Central < ApplicationRecord
  self.primary_key = "centralable_id"
  belongs_to :centralable, polymorphic: true

  # has_many :link_sources, class_name: "Link", foreign_key: "source_id", primary_key: "centralable_id"
  # has_many :link_destinations, class_name: "Link", foreign_key: "destination_id", primary_key: "centralable_id"
  has_many :links, class_name: "Link", foreign_key: "source_id", primary_key: "centralable_id"
  has_many :backlinks, class_name: "Link", foreign_key: "destination_id", primary_key: "centralable_id"
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/date_accuracy.rb
# Serves the constant DATE_ACCURACY_MASK
# https://stackoverflow.com/questions/22894649/rails-partial-dates
module DateAccuracy
  DATE_ACCURACY_MASK = {year: 4, month: 6, day: 7}.freeze
  DATE_ACCURACY_VALUES = DATE_ACCURACY_MASK.map { |key, value| [key, key.to_s, value] }.flatten.freeze
end

app/models/edition.rb
class Edition < ApplicationRecord
  include Centralable
  include Linkable

  delegated_type :editionable, types: %w[AlbumEdition SongEdition]

  belongs_to :archetype
  has_many :sections, class_name: "EditionSection", dependent: :destroy
end

app/models/import.rb
module Import
  def self.ignite(import_order)
    order = Order.new(import_order)
    workflow = order.build_workflow
    workflow.call
  end
end

app/models/import_order.rb
class ImportOrder < ApplicationRecord
  belongs_to :import_order, optional: true
  belongs_to :user

  delegated_type :import_orderable, types: %w[MusicbrainzImportOrder]
  accepts_nested_attributes_for :import_orderable

  delegate_missing_to :import_orderable
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :source, class_name: "Central", primary_key: :centralable_id, inverse_of: :links
  belongs_to :destination, class_name: "Central", primary_key: :centralable_id, inverse_of: :backlinks
  belongs_to :link_kind
end

app/models/link_kind.rb
class LinkKind < ApplicationRecord
  has_many :links, dependent: :restrict_with_error

  validates :name, presence: true, uniqueness: true
end

app/models/participant.rb
class Participant < ApplicationRecord
  include Centralable
  include Linkable
  include Periodable

  belongs_to :import_order, optional: true
  has_many :artist_credit_participants, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :sort_name, presence: true

  before_validation :ensure_sort_name_has_a_value

  private

  def ensure_sort_name_has_a_value
    return if sort_name.present?
    self.sort_name = name
  end
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/song_archetype.rb
class SongArchetype < ApplicationRecord
  # TODO: are there really codes for discogs, musicbrainz and wikidata?
  include Archetypeable
end

app/models/song_edition.rb
class SongEdition < ApplicationRecord
  # TODO: are there really codes for discogs, musicbrainz and wikidata?
  include Editionable
end

app/models/url.rb
class Url < ApplicationRecord
  include Centralable
  include Linkable

  validates :address, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  has_many :import_orders, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }

  validates :email_address, presence: true, uniqueness: true, format: {with: URI::MailTo::EMAIL_REGEXP}
  validates :password, presence: true, length: {minimum: 6}
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  skip_before_action :require_authentication, only: %i[show index]
  before_action :set_participant, only: %i[show edit update destroy]

  # GET /participants or /participants.json
  def index
    @participants = Participant.all
  end

  # GET /participants/1 or /participants/1.json
  def show
  end

  # GET /participants/new
  def new
    @participant = Participant.new
  end

  # GET /participants/1/edit
  def edit
  end

  # POST /participants or /participants.json
  def create
    @participant = Participant.new(participant_params)

    respond_to do |format|
      if @participant.save
        format.html { redirect_to participant_url(@participant), notice: "Participant was successfully created." }
        format.json { render :show, status: :created, location: @participant }
      else
        format.html { render :new, status: :unprocessable_content }
        format.json { render json: @participant.errors, status: :unprocessable_content }
      end
    end
  end

  # PATCH/PUT /participants/1 or /participants/1.json
  def update
    respond_to do |format|
      if @participant.update(participant_params)
        format.html { redirect_to participant_url(@participant), notice: "Participant was successfully updated." }
        format.json { render :show, status: :ok, location: @participant }
      else
        format.html { render :edit, status: :unprocessable_content }
        format.json { render json: @participant.errors, status: :unprocessable_content }
      end
    end
  end

  # DELETE /participants/1 or /participants/1.json
  def destroy
    @participant.destroy!

    respond_to do |format|
      format.html { redirect_to participants_url, notice: "Participant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_participant
    @participant = Participant.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def participant_params
    params.require(:participant).permit(:name, :sort_name, :disambiguation, :begin_date, :begin_date_accuracy, :end_date, :end_date_accuracy, :import_order_id, :discogs_code, :imdb_code, :musicbrainz_code, :tmdb_code, :wikidata_code)
  end
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/participants_helper.rb
module ParticipantsHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/participants/_form.html.erb
<%= form_with(model: participant) do |form| %>
  <% if participant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(participant.errors.count, "error") %> prohibited this participant from being saved:</h2>

      <ul>
        <% participant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_area :name %>
  </div>

  <div>
    <%= form.label :sort_name, style: "display: block" %>
    <%= form.text_area :sort_name %>
  </div>

  <div>
    <%= form.label :disambiguation, style: "display: block" %>
    <%= form.text_area :disambiguation %>
  </div>

  <div>
    <%= form.label :begin_date, style: "display: block" %>
    <%= form.date_field :begin_date %>
  </div>

  <div>
    <%= form.label :begin_date_accuracy, style: "display: block" %>
    <%= form.number_field :begin_date_accuracy %>
  </div>

  <div>
    <%= form.label :end_date, style: "display: block" %>
    <%= form.date_field :end_date %>
  </div>

  <div>
    <%= form.label :end_date_accuracy, style: "display: block" %>
    <%= form.number_field :end_date_accuracy %>
  </div>

  <div>
    <%= form.label :import_order_id, style: "display: block" %>
    <%= form.text_field :import_order_id %>
  </div>

  <div>
    <%= form.label :discogs_code, style: "display: block" %>
    <%= form.number_field :discogs_code %>
  </div>

  <div>
    <%= form.label :imdb_code, style: "display: block" %>
    <%= form.number_field :imdb_code %>
  </div>

  <div>
    <%= form.label :musicbrainz_code, style: "display: block" %>
    <%= form.text_field :musicbrainz_code %>
  </div>

  <div>
    <%= form.label :tmdb_code, style: "display: block" %>
    <%= form.number_field :tmdb_code %>
  </div>

  <div>
    <%= form.label :wikidata_code, style: "display: block" %>
    <%= form.number_field :wikidata_code %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/participants/_participant.html.erb
<div id="<%= dom_id participant %>">
  <p>
    <strong>Name:</strong>
    <%= participant.name %>
  </p>

  <p>
    <strong>Sort name:</strong>
    <%= participant.sort_name %>
  </p>

  <p>
    <strong>Disambiguation:</strong>
    <%= participant.disambiguation %>
  </p>

  <p>
    <strong>Begin date:</strong>
    <%= participant.begin_date %>
  </p>

  <p>
    <strong>Begin date mask:</strong>
    <%= participant.begin_date_accuracy %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= participant.end_date %>
  </p>

  <p>
    <strong>End date mask:</strong>
    <%= participant.end_date_accuracy %>
  </p>

  <p>
    <strong>Import order:</strong>
    <%= participant.import_order_id %>
  </p>

  <p>
    <strong>Discogs code:</strong>
    <%= participant.discogs_code %>
  </p>

  <p>
    <strong>Imdb code:</strong>
    <%= participant.imdb_code %>
  </p>

  <p>
    <strong>Musicbrainz code:</strong>
    <%= participant.musicbrainz_code %>
  </p>

  <p>
    <strong>Tmdb code:</strong>
    <%= participant.tmdb_code %>
  </p>

  <p>
    <strong>Wikidata code:</strong>
    <%= participant.wikidata_code %>
  </p>

</div>

app/views/participants/edit.html.erb
<h1>Editing participant</h1>

<%= render "form", participant: @participant %>

<br>

<div>
  <%= link_to "Show this participant", @participant %> |
  <%= link_to "Back to participants", participants_path %>
</div>

app/views/participants/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Participants</h1>

<div id="participants">
  <% @participants.each do |participant| %>
    <%= render participant %>
    <p>
      <%= link_to "Show this participant", participant %>
    </p>
  <% end %>
</div>

<%= link_to "New participant", new_participant_path %>

app/views/participants/new.html.erb
<h1>New participant</h1>

<%= render "form", participant: @participant %>

<br>

<div>
  <%= link_to "Back to participants", participants_path %>
</div>

app/views/participants/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @participant %>

<div>
  <%= link_to "Edit this participant", edit_participant_path(@participant) %> |
  <%= link_to "Back to participants", participants_path %>

  <%= button_to "Destroy this participant", @participant, method: :delete %>
</div>