config/routes.rb
Rails.application.routes.draw do
  resource :registrations, only: [:new, :create]
  resource :session
  resources :passwords, param: :token
  resources :urls
  resources :links
  resources :link_kinds
  resources :edition_positions
  resources :edition_sections
  resources :editions
  resources :archetypes
  resources :artist_credit_participants
  resources :artist_credits
  resources :participants

  get "home", to: "home#index"
  resources :import_orders
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource :password, only: [:edit, :update]
  namespace :identity do
    resource :email, only: [:edit, :update]
    resource :email_verification, only: [:edit, :create]
    resource :password_reset, only: [:new, :edit, :create, :update]
  end
  root "main#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/album_edition.rb
class AlbumEdition < ApplicationRecord
  include Editionable
end

app/models/archetype.rb
class Archetype < ApplicationRecord
  include Centralable
  include Linkable

  delegated_type :archetypeable, types: %w[AlbumArchetype SongArchetype]

  belongs_to :artist_credit, optional: true
  has_many :editions
end

app/models/artist_credit.rb
class ArtistCredit < ApplicationRecord
  has_many :participants, class_name: "ArtistCreditParticipant", dependent: :destroy

  before_validation :ensure_name_has_a_value

  validates :name, presence: true, uniqueness: true

  private

  def ensure_name_has_a_value
    return if name.present?

    pairs = participants.map { |acp| [acp.name, join_phrase_for(acp)] }.flatten
    pairs.pop # ignore the last join_phrase
    self.name = pairs.join
  end

  def join_phrase_for(artist_credit_participant)
    artist_credit_participant.join_phrase || " "
  end
end

app/models/central.rb
class Central < ApplicationRecord
  self.primary_key = "centralable_id"
  belongs_to :centralable, polymorphic: true

  # has_many :link_sources, class_name: "Link", foreign_key: "source_id", primary_key: "centralable_id"
  # has_many :link_destinations, class_name: "Link", foreign_key: "destination_id", primary_key: "centralable_id"
  has_many :links, class_name: "Link", foreign_key: "source_id", primary_key: "centralable_id"
  has_many :backlinks, class_name: "Link", foreign_key: "destination_id", primary_key: "centralable_id"
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/date_accuracy.rb
# Serves the constant DATE_ACCURACY_MASK
# https://stackoverflow.com/questions/22894649/rails-partial-dates
module DateAccuracy
  DATE_ACCURACY_MASK = {year: 4, month: 6, day: 7}.freeze
  DATE_ACCURACY_VALUES = DATE_ACCURACY_MASK.map { |key, value| [key, key.to_s, value] }.flatten.freeze
end

app/models/edition.rb
class Edition < ApplicationRecord
  include Centralable
  include Linkable

  delegated_type :editionable, types: %w[AlbumEdition SongEdition]

  belongs_to :archetype
  has_many :sections, class_name: "EditionSection", dependent: :destroy
end

app/models/import.rb
module Import
  def self.ignite(import_order)
    order = Order.new(import_order)
    workflow = order.build_workflow
    workflow.call
  end
end

app/models/import_order.rb
class ImportOrder < ApplicationRecord
  belongs_to :import_order, optional: true
  belongs_to :user

  delegated_type :import_orderable, types: %w[MusicbrainzImportOrder]
  accepts_nested_attributes_for :import_orderable

  delegate_missing_to :import_orderable
end

app/models/link.rb
class Link < ApplicationRecord
  belongs_to :source, class_name: "Central", primary_key: :centralable_id, inverse_of: :links
  belongs_to :destination, class_name: "Central", primary_key: :centralable_id, inverse_of: :backlinks
  belongs_to :link_kind
end

app/models/link_kind.rb
class LinkKind < ApplicationRecord
  has_many :links, dependent: :restrict_with_error

  validates :name, presence: true, uniqueness: true
end

app/models/participant.rb
class Participant < ApplicationRecord
  include Centralable
  include Linkable
  include Periodable

  belongs_to :import_order, optional: true
  has_many :artist_credit_participants, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :sort_name, presence: true

  before_validation :ensure_sort_name_has_a_value

  private

  def ensure_sort_name_has_a_value
    return if sort_name.present?
    self.sort_name = name
  end
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/song_archetype.rb
class SongArchetype < ApplicationRecord
  # TODO: are there really codes for discogs, musicbrainz and wikidata?
  include Archetypeable
end

app/models/song_edition.rb
class SongEdition < ApplicationRecord
  # TODO: are there really codes for discogs, musicbrainz and wikidata?
  include Editionable
end

app/models/url.rb
class Url < ApplicationRecord
  include Centralable
  include Linkable

  validates :address, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy
  has_many :import_orders, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }

  validates :email_address, presence: true, uniqueness: true, format: {with: URI::MailTo::EMAIL_REGEXP}
  validates :password, presence: true, length: {minimum: 6}
end

app/controllers/archetypes_controller.rb
class ArchetypesController < ApplicationController
  skip_before_action :require_authentication, only: [:show, :index]
  before_action :set_archetype, only: %i[show edit update destroy]

  # GET /archetypes or /archetypes.json
  def index
    @archetypes = Archetype.all
  end

  # GET /archetypes/1 or /archetypes/1.json
  def show
  end

  # GET /archetypes/new
  def new
    @archetype = Archetype.new
  end

  # GET /archetypes/1/edit
  def edit
  end

  # POST /archetypes or /archetypes.json
  def create
    @archetype = Archetype.new(archetype_params)

    respond_to do |format|
      if @archetype.save
        format.html { redirect_to archetype_url(@archetype), notice: "Archetype was successfully created." }
        format.json { render :show, status: :created, location: @archetype }
      else
        format.html { render :new, status: :unprocessable_content }
        format.json { render json: @archetype.errors, status: :unprocessable_content }
      end
    end
  end

  # PATCH/PUT /archetypes/1 or /archetypes/1.json
  def update
    respond_to do |format|
      if @archetype.update(archetype_params)
        format.html { redirect_to archetype_url(@archetype), notice: "Archetype was successfully updated." }
        format.json { render :show, status: :ok, location: @archetype }
      else
        format.html { render :edit, status: :unprocessable_content }
        format.json { render json: @archetype.errors, status: :unprocessable_content }
      end
    end
  end

  # DELETE /archetypes/1 or /archetypes/1.json
  def destroy
    @archetype.destroy!

    respond_to do |format|
      format.html { redirect_to archetypes_url, notice: "Archetype was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_archetype
    @archetype = Archetype.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def archetype_params
    # params.require(:archetype).permit(:title, :artist_credit_id, :archetypeable_type, :archetypeable_id)
    params.require(:archetype).permit(:title, :archetypeable_type, :archetypeable_id)
  end
end

app/helpers/archetypes_helper.rb
module ArchetypesHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/archetypes/_archetype.html.erb
<div id="<%= dom_id archetype %>">
  <p>
    <strong>Title:</strong>
    <%= archetype.title %>
  </p>

  <p>
    <strong>Archetypeable type:</strong>
    <%= archetype.archetypeable_type %>
  </p>

  <p>
    <strong>Archetypeable:</strong>
    <%= archetype.archetypeable_id %>
  </p>

</div>

app/views/archetypes/_form.html.erb
<%= form_with(model: archetype) do |form| %>
  <% if archetype.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(archetype.errors.count, "error") %> prohibited this archetype from being saved:</h2>

      <ul>
        <% archetype.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :artist_credit_id, style: "display: block" %>
    <%= form.text_field :artist_credit_id %>
  </div>

  <div>
    <%= form.label :archetypeable_type, style: "display: block" %>
    <%= form.text_field :archetypeable_type %>
  </div>

  <div>
    <%= form.label :archetypeable_id, style: "display: block" %>
    <%= form.text_field :archetypeable_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/archetypes/edit.html.erb
<h1>Editing archetype</h1>

<%= render "form", archetype: @archetype %>

<br>

<div>
  <%= link_to "Show this archetype", @archetype %> |
  <%= link_to "Back to archetypes", archetypes_path %>
</div>

app/views/archetypes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Archetypes</h1>

<div id="archetypes">
  <% @archetypes.each do |archetype| %>
    <%= render archetype %>
    <p>
      <%= link_to "Show this archetype", archetype %>
    </p>
  <% end %>
</div>

<%= link_to "New archetype", new_archetype_path %>

app/views/archetypes/new.html.erb
<h1>New archetype</h1>

<%= render "form", archetype: @archetype %>

<br>

<div>
  <%= link_to "Back to archetypes", archetypes_path %>
</div>

app/views/archetypes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @archetype %>

<div>
  <%= link_to "Edit this archetype", edit_archetype_path(@archetype) %> |
  <%= link_to "Back to archetypes", archetypes_path %>

  <%= button_to "Destroy this archetype", @archetype, method: :delete %>
</div>