config/routes.rb
Rails.application.routes.draw do
  resource :registrations, only: [:new, :create]
  resource :session
  resources :passwords, param: :token
  resources :urls
  resources :links
  resources :link_kinds
  resources :edition_positions
  resources :edition_sections
  resources :editions
  resources :archetypes
  resources :artist_credit_participants
  resources :artist_credits
  resources :participants

  get "home", to: "home#index"
  resources :import_orders
  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [:index, :show, :destroy]
  resource :password, only: [:edit, :update]
  namespace :identity do
    resource :email, only: [:edit, :update]
    resource :email_verification, only: [:edit, :create]
    resource :password_reset, only: [:new, :edit, :create, :update]
  end
  root "main#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/import_order.rb
class ImportOrder < ApplicationRecord
  belongs_to :import_order, optional: true
  belongs_to :user

  delegated_type :import_orderable, types: %w[MusicbrainzImportOrder]
  accepts_nested_attributes_for :import_orderable

  delegate_missing_to :import_orderable
end

app/controllers/import_orders_controller.rb
class ImportOrdersController < ApplicationController
  before_action :set_import_order, only: %i[show edit update destroy]
  after_action :place_job, only: %i[create]

  # GET /import_orders or /import_orders.json
  def index
    @import_orders = Current.user.import_orders
  end

  # GET /import_orders/1 or /import_orders/1.json
  def show
  end

  # GET /import_orders/new
  def new
    @import_order = Current.user.import_orders.build
  end

  # GET /import_orders/1/edit
  def edit
  end

  # POST /import_orders or /import_orders.json
  def create
    @import_order = Current.user.import_orders.build(import_order_params)

    respond_to do |format|
      if @import_order.save
        format.html { redirect_to url_for(@import_order), notice: "Import order was successfully created." }
        format.json { render :show, status: :created, location: @import_order }
      else
        format.html { render :new, status: :unprocessable_content }
        format.json { render json: @import_order.errors, status: :unprocessable_content }
      end
    end
  end

  # PATCH/PUT /import_orders/1 or /import_orders/1.json
  def update
    respond_to do |format|
      if @import_order.update(import_order_params)
        format.html { redirect_to import_order_url(@import_order), notice: "Import order was successfully updated." }
        format.json { render :show, status: :ok, location: @import_order }
      else
        format.html { render :edit, status: :unprocessable_content }
        format.json { render json: @import_order.errors, status: :unprocessable_content }
      end
    end
  end

  # DELETE /import_orders/1 or /import_orders/1.json
  def destroy
    @import_order.destroy

    respond_to do |format|
      format.html { redirect_to import_orders_url, notice: "Import order was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_import_order
    @import_order = Current.user.import_orders.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def import_order_params
    (import_order_params_by_uri || params)
      .require(:import_order)
      .permit(:import_orderable_type, {import_orderable_attributes: [:kind, :code, :uri]})
  end

  def import_order_params_by_uri
    uri_string = params.dig(:import_order, :uri)
    return if uri_string.blank?

    import_order_uri = ImportOrderUri.build(uri_string)

    ActionController::Parameters.new(
      {
        import_order: {
          import_orderable_type: import_order_uri.import_order_type,
          import_orderable_attributes: {
            kind: import_order_uri.kind_and_code.kind,
            code: import_order_uri.kind_and_code.code,
            uri: uri_string
          }
        }
      }
    )
  end

  def place_job
    return if @import_order.new_record?

    Rails.logger.info("controller: #{@import_order.inspect}")

    case @import_order.import_orderable_type
    when "MusicbrainzImportOrder"
      # TODO: choose the right Job depending on :kind
      Rails.logger.debug("ImportOrder#uri: #{@import_order.uri.inspect}")
      ImportMusicbrainzReleaseJob.perform_later(@import_order)
    else
      raise "can't enqueue job for #{@import_order}"
    end
  end
end

app/helpers/import_orders_helper.rb
module ImportOrdersHelper
end

app/views/import_orders/_form.html.erb
<%= form_with(model: import_order) do |form| %>
  <% if import_order.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(import_order.errors.count, "error") %> prohibited this import_order from being saved:</h2>

      <ul>
        <% import_order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :code, style: "display: block" %>
    <%= form.text_field :code %>
  </div>

  <div>
    <%= form.label :kind, style: "display: block" %>
    <%= form.text_field :kind %>
  </div>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.text_field :state %>
  </div>

  <div>
    <%= form.label :type, style: "display: block" %>
    <%= form.text_field :type %>
  </div>

  <div>
    <%= form.label :uri, style: "display: block" %>
    <%= form.text_field :uri %>
  </div>

  <div>
    <%= form.label :import_order_id, style: "display: block" %>
    <%= form.text_field :import_order_id %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/import_orders/_import_order.html.erb
<div id="<%= dom_id import_order %>">
  <p>
    <strong>Kind:</strong>
    <%= import_order.kind %>
  </p>

  <p>
    <strong>State:</strong>
    <%= import_order.state %>
  </p>

  <p>
    <strong>Uri:</strong>
    <%= import_order.uri %>
  </p>

  <p>
    <strong>Import order:</strong>
    <%= import_order.import_order_id %>
  </p>

  <p>
    <strong>User:</strong>
    <%# = import_order.user_id %>
  </p>

</div>

app/views/import_orders/edit.html.erb
<h1>Editing import order</h1>

<%= render "form", import_order: @import_order %>

<br>

<div>
  <%= link_to "Show this import order", @import_order %> |
  <%= link_to "Back to import orders", import_orders_path %>
</div>

app/views/import_orders/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Import orders</h1>

<div id="import_orders">
  <% @import_orders.each do |import_order| %>
    <%= render import_order %>
    <p>
      <%= link_to "Show this import order", import_order %>
    </p>
  <% end %>
</div>

<%= link_to "New import order", new_import_order_path %>

app/views/import_orders/new.html.erb
<h1>New import order</h1>

<%= render "form", import_order: @import_order %>

<br>

<div>
  <%= link_to "Back to import orders", import_orders_path %>
</div>

app/views/import_orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @import_order %>

<div>
  <%= link_to "Edit this import order", edit_import_order_path(@import_order) %> |
  <%= link_to "Back to import orders", import_orders_path %>

  <%= button_to "Destroy this import order", @import_order, method: :delete %>
</div>